### PR TITLE
Implement TLS Observatory scans

### PR DESCRIPTION
**Pull request by caggle**
This uses dedicated handlers (as experimented in https://github.com/mozilla/vautomator-serverless/pull/18) as well as test classes for them, using `moto`.

It's a work in progress, as tests for performing the actual TLS scan is not implemented yet.

### CODE REVIEW

**Comment by caggle** [comment]
Ready for review!

**Comment by claudijd** [comment]
@caggle you have this marked as a WIP, so I'm going to forego merging, but willing to when you say so.

**Comment by caggle** [comment]
@claudijd thanks, this is actually a few more commits away still, I want to write some working code under examples. Sorry for marking it for review early-ish. Will probably be ready in a day or so.

**Comment by caggle** [comment]
Ready for review.

**Pull request merged**
