### PR TITLE
add extract and arg parser support

### PR DESCRIPTION
**Pull request by gdestuynder**

### CODE REVIEW

**Comment by gdestuynder** [comment]
note, this code should be ported to the on-demand script as well, and i would recommend integrating both scripts into a single one - for ease of use

**Comment by caggle** [comment]
Thank you @gdestuynder! It looks good, I will look into merging this as soon as I complete working on another PR. Apologies if you don't see this merged right away.

Also, I will likely create a new branch with your suggestions/fixes, instead of merging into `master`. Hope that works.

**Comment by gdestuynder** [comment]
its your repo, its up to you.i dont know why a branch is needed unless you dont like these changes though, but really, thats up to you. you can also refuse the pr i wont be offended!

**Comment by caggle** [comment]
It's not that I don't like the changes, it's that the changes are incomplete :)

I will need to apply them to the other client(s), possibly integrate them into a single client, plus I am close to implementing a scan-all endpoint using step functions, I may include that in these clients.

**Comment by caggle** [comment]
Work for this is underway in https://github.com/mozilla/vautomator-serverless/pull/43

**Pull request closed without merging**
